apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - './infra/k8s/*'
build:
  local:
    push: false
  artifacts:
    - image: gustavocondezo/currency-conversion
      context: backend/currency-conversion #Caarpeta donde esta
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gustavocondezo/currency-exchange
      context: backend/currency-exchange
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
