apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-read-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bd-read
  template:
    metadata:
      labels:
        app: bd-read
    spec:
      containers:
        - name: bd-read
          image: redis
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "512Mi"
              cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
  name: bd-read-srv
spec:
  selector:
    app: bd-read
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
