apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-every-30-seg
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: container-cron
              image: appropriate/curl
              command:
                ["/bin/sh", "-c",
                "
                    curl -X POST http://currency-conversion-srv:3000/conversions;
                    sleep 30;
                    curl -X POST http://currency-conversion-srv:3000/conversions;
                "]
          restartPolicy: OnFailure

