apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-lb
spec:
  selector:
    app: currency-exchange
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
