apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-zookeeper
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.0.1
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"

        - name: kafka
          image: confluentinc/cp-kafka:7.0.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "kafka-srv:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:29092,PLAINTEXT_HOST://kafka-srv:9092"
            - name:  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name:  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_JMX_PORT
              value: "9991"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-srv

spec:
  selector:
    app: kafka-zookeeper # Selector que apunta al deployment que incluye Kafka y Zookeeper
  ports:
    - name: kafka
      port: 9092 # Puerto del contenedor Kafka
      targetPort: 9092 # Puerto del contenedor Kafka
    - name: zookeeper
      port: 2181 # Puerto del contenedor Kafka
      targetPort: 2181 # Puerto del contenedor Kafka


