apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-sync-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-sync
  template:
    metadata:
      labels:
        app: todo-sync
    spec:
      containers:
        - name: todo-sync
          image: gustavocondezo/todo-sync
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "512Mi"
              cpu: "512m"
          env:
            - name: PORT
              value: '3000'
            - name: BD_HOST
              value: 'bd-read-srv'
            - name: BD_PORT
              value: '6379'
            - name: KAFKA_BROKER
              value: 'kafka-srv:9092'

#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: todo-sync-srv
#spec:
#  selector:
#    app: todo-sync
#    type: ClusterIP
#  ports:
#    - name: todo-sync
#      protocol: TCP
#      port: 4000
#      targetPort: 4000
